version: '3'

services:
  farsantes.localhost:
    # nginx config
    image: nginx
    volumes:
      - .:/usr/share/nginx/html:ro

    # uncomment to use Aapche HTTPD Server
    #        image: httpd:2.4-alpine
    #        volumes:
    #            - ./files:/usr/local/apache2/htdocs:ro

    # Uncomment to use Caddeserver
    #        image: caddy/caddy:scratch
    #        command: file-server --root /files --listen 0.0.0.0:80
    #        volumes:
    #            - ./files:/files:ro

    # container_name: static-files
    restart: on-failure
    networks:
      - web
    labels:
      - traefik.enable=true
      # - traefik.http.routers.farsantes.entrypoints=http
      # Match on the hostname and the path
      - traefik.http.routers.farsantes.rule=Host(`farsantes.localhost`)
      # - traefik.http.routers.static-files.tls=true
      # - traefik.http.routers.static-files.tls.certresolver=le
      # - traefik.http.services.farsantes.loadbalancer.server.port=80

      # Define a new middleware to strip the URL prefix before sending it to static-files
      # - traefik.http.middlewares.static-files-stripprefix.stripprefix.prefixes=/static

      # tell Traefik which middlewares we want to use on this container
      # - traefik.http.routers.static-files.middlewares=gzip@docker,static-files-stripprefix@docker

networks:
  web:
    external: true